scalar BigDecimalU256

# TODO find a way to add enum
# enum TroveStatus {
#   active
#   closed
#   liquidated
#   redeemed
# }

type BorrowerInfo {
  id: ID! # "borrowerAddress", e.g. "0x0000000000000000000000000000000000000000"
  nextOwnerIndexes: [Int!]!
  troves: Int!
  trovesByCollateral: [Int!]!
}

type Collateral {
  id: ID! # "collIndex", e.g. "0"
  collIndex: Int!
  minCollRatio: BigDecimalU256!
  troves: [Trove!]! @derivedFrom(field: "collateral")
  addresses: CollateralAddresses! @derivedFrom(field: "collateral")
}

type CollateralAddresses {
  id: ID! # "collIndex", e.g. "0"
  collateral: Collateral!
  borrowerOperations: String!
  sortedTroves: String!
  stabilityPool: String!
  token: String!
  troveManagerEventsEmitter: String!
  troveManager: String!
  troveNft: String!
}

type InterestRateBracket {
  id: ID! # "collIndex:rateFloored", e.g. "0:44000000000000000"
  collateral: Collateral!
  rate: BigDecimalU256!
  totalDebt: BigDecimalU256!
}

type InterestBatch {
  id: ID! # "collIndex:batchManager", e.g. "0:0x0000000000000000000000000000000000000000"
  collateral: Collateral!
  batchManager: String!
  debt: BigDecimalU256!
  coll: BigDecimalU256!
  annualInterestRate: BigDecimalU256!
  annualManagementFee: BigDecimalU256!
  troves: [Trove!]! @derivedFrom(field: "interestBatch")
}

type Trove {
  id: ID! # "collIndex:collId", e.g. 0:0x1731afc858cad2708001a4f71851f9f775729c22f47df7c4360b1e416fd0f2de
  borrower: String!
  collateral: Collateral!
  closedAt: Int
  createdAt: Int!
  mightBeLeveraged: Boolean!
  status: String! #TroveStatus
  updatedAt: Int!
  debt: BigDecimalU256!
  deposit: BigDecimalU256!
  interestBatch: InterestBatch
  interestRate: BigDecimalU256!
  stake: BigDecimalU256!
  troveId: String!
}
